config/routes.rb
Rails.application.routes.draw do
  root to: 'tasks#index'
  get "tasks/new", to: "tasks#new"
  post "tasks", to: "tasks#create"
  get "tasks/:id", to: "tasks#show", as: :task
  get "tasks/:id/edit", to: "tasks#edit", as: :edit_task
  patch "tasks/:id", to: "tasks#update"
  delete "tasks/:id", to: "tasks#destroy", as: :destroy_task
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :select_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show

  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_par)
    @task.save
    redirect_to task_path(@task)
  end

  def edit

  end

  def update
    @task.update(task_par)
    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy
    redirect_to root_path, status: :see_other
  end

  private

  def task_par
    params.require(:task).permit(:title, :details, :completed)
  end

  def select_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/task_helper.rb
module TaskHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/task/index.html.erb
<h1>hello</h1>

<ul>
  <% @tasks.each do |task| %>
    <li><%= task.name %></li>
  <% end %>
</ul>

app/views/tasks/edit.html.erb
<div class="m-3">
  <%= form_for(@task) do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.label :details %>
    <%= f.text_field :details %>
    <%# <%= f.check_box :completed %>
    <label>
          <%= f.check_box :completed %> Completed
        </label>
    <%= f.submit %>
  <% end %>
</div>

app/views/tasks/index.html.erb
<h1>hello</h1>

<ul>
  <% @tasks.each do |task| %>
    <li><%= link_to task.title, task_path(task) %></li>
  <% end %>
</ul>

<%= link_to "Add task", tasks_new_path %>

app/views/tasks/new.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
<ul class="list-unstyled m-3">
  <li><%= @task.title%></li>
  <li><%= @task.details%></li>
  <%# <li><%= @task.completed ? <i class="fa fa-check-square-o"></i> This task is completed : <i class="fa fa-square-o"></i> This task is not completed %>
    <% if @task.completed %>
    <i class="fa-solid fa-square-check"></i> This task is completed
  <% else %>
    <i class="fa-regular fa-square"></i> This task is not completed yet
  <% end %>
</ul>

<%= link_to "Edit task", edit_task_path %>
<%= link_to "Delete",
  task_path(@task),
  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
%>
<%= link_to "Home", root_path %>